jwt:
  secret: 'eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIi'

server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userportal
    password: 05377048490m
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
